galaxy_info:
  role_name: sysstat
  author: Robert Brightling
  description: Install and configure sysstat system montioring

  license: LGPL-3.0-or-later

  min_ansible_version: "2.18"

  platforms:
    - name: Debian
      versions:
        - bookworm

  galaxy_tags:
    - sysstat
    - monitoring

dependencies: []
