galaxy_info:
  author: Robert Brightling
  description: Install and configure rkhunter

  license: LGPL-3.0

  min_ansible_version: 2.10

  platforms:
    - name: Debian
      versions:
        - Buster
    - name: EL
      versions:
        - 8

  galaxy_tags:
    - rkhunter
    - security
    - rootkit

dependencies: []
