galaxy_info:
  author: Robert Brightling
  description: Install and configure rkhunter

  license: LGPL-3.0

  min_ansible_version: "2.18"

  platforms:
    - name: Debian
      versions:
        - bookworm

  galaxy_tags:
    - rkhunter
    - security
    - rootkit

dependencies: []
