---
# Debian specific tasks

- name: Copy sysstat system default config
  ansible.builtin.copy:
    src: sysstat.default
    dest: /etc/default/sysstat
    mode: "0644"
    owner: root
    group: root
  become: true
  tags:
    - configure

- name: Template sysstat cron file
  ansible.builtin.template:
    src: sysstat.cron.j2
    dest: "{{ sysstat__cron_file_path }}"
    owner: root
    group: root
    mode: "0644"
  become: true
  tags:
    - configure
