---
# redhat specific tasks

- name: Make sysstat-collect timer override directory
  ansible.builtin.file:
    path: /etc/systemd/system/sysstat-collect.timer.d
    state: directory
    mode: "0755"
    owner: root
    group: root
  become: true
  tags:
    - setup

- name: Template systemd sysstat-collect timer override
  ansible.builtin.template:
    src: sysstat-collect.timer.override.conf.j2
    dest: /etc/systemd/system/sysstat-collect.timer.d/override.conf
    mode: "0644"
    owner: root
  become: true
  tags:
    - configure
  notify:
    - Restart sysstat-collect timer

- name: Start and enable sysstat timer services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items: "{{ sysstat__systemd_timers }}"
  become: true
  tags:
    - service
