galaxy_info:
  role_name: sudo
  author: Robert Brightling
  description: Manage systems sudoers

  license: LGPL-3.0-or-later

  min_ansible_version: "2.18"

  platforms:
    - name: Debian
      versions:
        - bookworm

  galaxy_tags:
    - sudo
    - sudoers

dependencies: []
