# Default shhd options
openssh_server__ciphers:
  - aes128-gcm@openssh.com
  - aes256-gcm@openssh.com 
  - chacha20-poly1305@openssh.com 
  - aes256-ctr
  - aes192-ctr
  - aes128-ctr

openssh_server__kex_algorithms:
  - diffie-hellman-group14-sha256
  - diffie-hellman-group16-sha512
  - diffie-hellman-group18-sha512
  - curve25519-sha256@libssh.org

# Specifies the available MAC (message authentication code) algorithms.
openssh_server__macs:
  - umac-128-etm@openssh.com
  - hmac-sha2-256-etm@openssh.com
  - hmac-sha2-512-etm@openssh.com
