---
- name: Converge
  hosts: all
  tasks:
    - name: set debian
      ansible.builtin.set_fact:
        rkhunter_scriptwhitelist:
          - "/bin/egrep"
          - "/bin/fgrep"
          - "/usr/bin/which"
          - "/usr/bin/ldd"
          - "/usr/sbin/adduser"
      when: ansible_os_family == "Debian"
    - name: installed base files
      package:
        name:
          - curl
          - grep
        state: present
      become: true
    - name: "Include rbrightling.system.rkhunter"
      include_role:
        name: "rbrightling.system.rkhunter"
