---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8
platforms:
  - name: instance
    image: ${MOLECULE_IMAGE:-debian:latest}
    pre_build_image: true
    privileged: ${MOLECULE_PRIVILEGED:-false}
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../roles/
verifier:
  name: testinfra
scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
      # - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
