---
# Tasks for Debian

- name: install python
  ansible.builtin.raw: 'test -e {{ ansible_node_python_path }} && echo ok || (apt -y update && apt -y install {{ ansible_node_python_packages|join(" ") }})'
  args:
    executable: /bin/bash
  register: raw_install_python
  changed_when: "'ok' not in raw_install_python.stdout"

- name: set /usr/bin/python using alternatives if not found
  ansible.builtin.raw: 'test -e /usr/bin/python && echo ok || update-alternatives --install /usr/bin/python python {{ ansible_node_python_path }} 1'
  args:
    executable: /bin/bash
  register: raw_alternatives_python
  changed_when: "'ok' not in raw_alternatives_python.stdout"

- name: install python apt module
  ansible.builtin.raw: >
    {{ ansible_node_python_path }} -c "import apt" &> /dev/null && echo ok || (apt -y update && apt -y install {{ ansible_node_python_apt_package }})
  args:
    executable: /bin/bash
  register: raw_install_python_apt
  changed_when: "'ok' not in raw_install_python_apt.stdout"
