---
dependency:
  name: galaxy
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
driver:
  name: "podman"
platforms:
  - name: instance
    image: "${MOLECULE_IMAGE:-debian:latest}"
    privileged: false
    pre_build_image: true
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../roles
verifier:
  name: testinfra
