---
dependency:
  name: galaxy
driver:
  name: podman
lint: |
    set -e
    yamllint .
    ansible-lint .
    flake8
platforms:
  - name: instance
    image: ${MOLECULE_IMAGE:-debian:latest}
    privileged: ${MOLECULE_PRIVILEGED:-false}
    pre_build_image: true
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../roles/
verifier:
  name: testinfra
