galaxy_info:
  role_name: aide
  author: Robert Brightling
  description: Install and manage AIDE (Advanced Intrusion Detection Environment).

  license: LGPL-3.0-or-later

  min_ansible_version: "2.18"

  platforms:
    - name: Debian
      versions:
        - bookworm

  galaxy_tags:
    - aide
    - security
    - system

dependencies: []
