---
dependency:
  name: galaxy
driver:
  name: podman
lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8
platforms:
  - name: instance
    image: ${MOLECULE_IMAGE:-debian:12}
    pre_build_image: true
    privileged: ${MOLECULE_PRIVILEGED:-false}
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../roles/
verifier:
  name: testinfra
