---
- name: Converge
  hosts: all
  tasks:
    - name: "Update cache"
      ansible.builtin.apt: 
        update_cache: true
      when: ansible_os_family == "Debian"
      when: 
    - name: "Include rbrightling.system.fail2ban"
      ansible.builtin.include_role:
        name: "fail2ban"
