---
- name: Converge
  hosts: all
  tasks:
    - name: "Update apt"
      ansible.builtin.apt:
        update_cache: true

    - name: "Include rbrightling.system.openssh_server"
      ansible.builtin.include_role:
        name: "rbrightling.system.openssh_server"
