---
dependency:
  name: galaxy
driver:
  options:
    managed: false
    login_cmd_template: "podman exec -ti {instance} bash"
    ansible_connection_options:
      ansible_connection: podman
lint: |
    set -e
    yamllint .
    ansible-lint .
    flake8
platforms:
  - name: instance
    image: docker.io/geerlingguy/docker-${MOLECULE_DISTRO:-debian12}-ansible:latest
    command: ""
    systemd: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    privileged: ${MOLECULE_PRIVILEGED:-false}
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: testinfra
