---
# tasks file for hosts

- name: Setup gather network facts
  ansible.builtin.setup:
    gather_subset: "!all,!min,network"

- name: Configure hosts file
  ansible.builtin.template:
    src: hosts.j2
    dest: "{{ hosts__file_path }}"
    mode: '0644'
    owner: root
    group: root
  become: true
