---
- name: Converge
  hosts: all
  vars:
    sudo_requiretty: false
  tasks:
    - name: "Include rbrightling.system.sudo"
      ansible.builtin.include_role:
        name: "rbrightling.system.sudo"
