---
name: "rbrightling.system.aide"

on:
  push:
    paths:
      - 'roles/aide/**'
      - 'molecule/aide/**'
      - '.github/workflows/aide.yml'
      - 'tox.ini'

jobs:
  call_reusable_workflow:
    uses: ./.github/workflows/reusable-ansible-test-role.yml
    with:
      role-name: 'aide'
