---
name: "rbrightling.system.ansible_node"

on:
  push:
    paths:
      - 'roles/ansible_node/**'
      - 'molecule/ansible_node/**'
      - '.github/workflows/ansible_node.yml'
      - 'tox.ini'

jobs:
  call_reusable_workflow:
    uses: ./.github/workflows/reusable-ansible-test-role.yml
    with:
      role-name: 'ansible_node'
