---
name: "rbrightling.system.auditd"

on:
  push:
    paths:
      - 'roles/auditd/**'
      - 'molecule/auditd/**'
      - '.github/workflows/auditd.yml'
      - 'tox.ini'

jobs:
  call_reuseable_workflow:
    uses: ./.github/workflows/reusable-ansible-test-role.yml
    with:
      role-name: 'auditd'
