---
name: "rbrightling.system.auditd"

on:
  push:
    paths:
      - 'roles/auditd/**'
      - 'molecule/auditd/**'
      - '.github/workflows/auditd.yml'
      - 'tox.ini'

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Ansible Lint
       uses: ansible/ansible-lint-action@master
       with:
         targets: "roles/auditd"
