---
name: "rbrightling.system.fail2ban"

on:
  push:
    paths:
      - 'roles/fail2ban/**'
      - 'molecule/fail2ban/**'
      - '.github/workflows/fail2ban.yml'
      - 'tox.ini'

jobs:
  call_reusable_workflow:
    uses: ./.github/workflows/reusable-ansible-test-role.yml
    with:
      role-name: 'fail2ban'
