---
name: "rbrightling.system.hosts"

on:
  push:
    paths:
      - 'roles/hosts/**'
      - 'molecule/hosts/**'
      - '.github/workflows/hosts.yml'
      - 'tox.ini'

jobs:
  call_reusable_workflow:
    uses: ./.github/workflows/reusable-ansible-test-role.yml
    with:
      role-name: 'hosts'
