---
name: "rbrightling.system.openssh_server"

on:
  push:
    paths:
      - 'roles/openssh_server/**'
      - 'molecule/openssh_server/**'
      - '.github/workflows/openssh_server.yml'
      - 'tox.ini'

jobs:
  call_reusable_workflow:
    uses: ./.github/workflows/reusable-ansible-test-role.yml
    with:
      role-name: 'openssh_server'
