---
name: Publish Collection to Ansible Galaxy

on:
  push:
    tags:
      - '*'

jobs:
  galaxy_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install Ansible
        run: |
          pip install ansible-base
      - name: Build galaxy collection
        run: |
          ansible-galaxy collection build
      - name: Publish collection to Ansible Galaxy
        run: |
          ansible-galaxy collection publish --api-key "$API_KEY" rbrightling-system-${GITHUB_REF/refs\/tags\//}.tar.gz
        env:
          API_KEY: ${{ secrets.GALAXY_API_KEY }}
