---
name: Publish Collection to Ansible Galaxy

on:
  push:
    tags:
      - '*'

jobs:
  galaxy_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Ansible Publish
        uses: ansible/ansible-publish-action@v1.0.0
        env:
          API_KEY: ${{ secrets.GALAXY_API_KEY }}
