---
name: "rbrightling.system.shadow_utils"

on:
  push:
    paths:
      - 'roles/shadow_utils/**'
      - 'molecule/shadow_utils/**'
      - '.github/workflows/shadow_utils.yml'
      - 'plugins/filter/shadow_utils.py'
      - 'tox.ini'

jobs:
  call_reusable_workflow:
    uses: ./.github/workflows/reusable-ansible-test-role.yml
    with:
      role-name: 'shadow_utils'
