---
name: "rbrightling.system.sudo"

on:
  push:
    paths:
      - 'roles/sudo/**'
      - 'molecule/sudo/**'
      - '.github/workflows/sudo.yml'
      - 'tox.ini'

jobs:
  call_reusable_workflow:
    uses: ./.github/workflows/reusable-ansible-test-role.yml
    with:
      role-name: 'sudo'
