---
name: "rbrightling.system.sysstat"

on:
  push:
    paths:
      - 'roles/sysstat/**'
      - 'molecule/sysstat/**'
      - '.github/workflows/sysstat.yml'
      - 'tox.ini'

jobs:
  call_reusable_workflow:
    uses: ./.github/workflows/reusable-ansible-test-role.yml
    with:
      role-name: 'sysstat'
